{{- $postgresPasswordValue := (randAlpha 16) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "$.Values.postgres.secret") }}
{{- if $secret }}
{{- $postgresPasswordValue = index $secret.data "password" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secrets.secret}}
  annotations:
    replicator.v1.mittwald.de/replicate-to: "wordpress"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.secrets.password | default $postgresPasswordValue | b64enc}}
  user: {{.Values.secrets.user | default "wordpress" | b64enc}}
