apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: databases
      database: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: databases
        database: redis

    spec:
      containers:
      - image: {{ .Values.image}}:{{ .Values.tag}}
        name: redis
        command: ["sh","-c","redis-server","--save", "20", "{{ .Values.db}}", "--loglevel", "warning"]
        ports:
        - containerPort: {{ .Values.port}}
          name: redis
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
        resources:
          limits:
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}
          requests:
            cpu: {{.Values.resources.requests.cpu}}
            memory: {{.Values.resources.requests.memory}}
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
