#TODO  Configurar variáveis do redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: databases
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: databases
    spec:
      containers:
      - image: {{ .Values.image}}:{{ .Values.redisVersion}}
        name: redis
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Values.redisSecret}}
              key: root_password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Values.redisSecret}}
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{.Values.redisSecret}}
              key: user
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: {{ .Values.port}}
          name: redis
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /var/lib/redis
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
