apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: wordpress
spec:
  ports:
    - port: {{ .Values.port}}
  selector:
    app: wordpress
    tier: databases
  clusterIP: None
