{{- $mysqlPasswordValue := (randAlpha 16) }}
{{- $mysqlRootPasswordValue := (randAlpha 16) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "$.Values.mysqlSecret") }}
{{- if $secret }}
{{- $mysqlPasswordValue = index $secret.data "password" }}
{{- $mysqlRootPasswordValue = index $secret.data "root_password" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.mysqlSecret}}
  annotations:
    replicator.v1.mittwald.de/replicate-to: "wordpress"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root_password: {{ .Values.rootPassword | default $mysqlRootPasswordValue | b64enc}}
  password: {{ .Values.password | default $mysqlPasswordValue | b64enc}}
  user: {{.Values.user | default "wordpress" | b64enc}}
